/*
 * File: app/view/modalLogin.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppLogin.view.modalLogin', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 242,
    itemId: 'modalLogin',
    padding: 20,
    width: 361,
    bodyPadding: '',
    closable: false,
    title: 'Efetue o login',
    titleAlign: 'center',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            layout: {
                type: 'vbox',
                align: 'stretch',
                padding: ''
            },
            items: [
                {
                    xtype: 'fieldset',
                    flex: 1,
                    title: 'Login',
                    items: [
                        {
                            xtype: 'form',
                            itemId: 'formLogin',
                            bodyPadding: 10,
                            dockedItems: [
                                {
                                    xtype: 'textfield',
                                    dock: 'top',
                                    fieldLabel: 'Usuário',
                                    name: 'email'
                                },
                                {
                                    xtype: 'textfield',
                                    dock: 'top',
                                    fieldLabel: 'Senha',
                                    name: 'senha',
                                    inputType: 'password'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    dock: 'top',
                                    fieldLabel: '',
                                    name: 'lembrar',
                                    boxLabel: 'Matenha-me conectado'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    layout: {
                                        type: 'hbox',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Entrar',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var dados = Ext.ComponentQuery.query('#formLogin')[0].getValues();

        fbAuth.signInWithEmailAndPassword(dados.email, dados.senha)
        .then(function(res) {
            localStorage.setItem('login', firebase.auth().getUid());
            location.reload();
        })
        .catch(function(error) {
            Ext.Msg.alert('Status', 'Usuário ou senha incorreta !!.');
        });

    }

});