/*
 * File: app/controller/Firebase.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppLogin.controller.Firebase', {
    extend: 'Ext.app.Controller',

    statics: {
        ListaDados: function(collection, fn) {
            fbFirestore.collection(collection).onSnapshot(function(list) {
                var data = [];

                list.forEach(function(obj){
                    var dados = obj.data();
                    dados.id = obj.id;
                    data.push(dados);
                });

                if(fn){
                    fn(data);
                }
            });
        },

        BuscarArquivo: function(name, fnSuccess, fnFailure) {
            fbStorage.ref(name).getDownloadURL().then(function(url) {
                if(fnSuccess){
                    fnSuccess(url);
                }
            }).catch(function(erro){
                if(fnSuccess){
                    fnSuccess(erro);
                }
            });
        },

        SalvarDados: function() {

        },

        SalvarArquivo: function() {

        },

        EditarDados: function() {

        },

        ExcluirDados: function(collection, id) {
            fbFirestore.collection(collection).doc(id).delete();
        },

        ExcluirArquivo: function(id) {
            var ref = fbStorage.ref();

            ref.child(id).delete();
        }
    }
});
